services:
  db:
    image: postgres:16
    container_name: wezet-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: wezet
      POSTGRES_PASSWORD: wezet_password
      POSTGRES_DB: wezet_db
    ports:
      - "5432:5432"
    volumes:
      - wezet_pgdata:/var/lib/postgresql/data

volumes:
  wezet_pgdata:
